<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-SIU2A5U" ignored="0" name="Test" tests="2" failures="1" timestamp="2023-08-01T20:00:37 IST" time="12.394" errors="0">
  <testcase name="alogincheck" time="0.038" classname="com.cjc.MTLoginCheck">
    <failure type="java.lang.AssertionError" message="expected [https://demo.guru99.com/test/newtours/index.ph] but found [https://demo.guru99.com/test/newtours/index.php]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.guru99.com/test/newtours/index.ph] but found [https://demo.guru99.com/test/newtours/index.php]
at com.cjc.MTLoginCheck.alogincheck(MTLoginCheck.java:74)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- alogincheck -->
  <testcase name="alogincheck1" time="3.507" classname="com.cjc.MTLoginCheck"/>
</testsuite> <!-- Test -->
